### ISSUE TITLE
Support for python3

### ISSUE THREAD

**Issue by falzm** [exoscale/pkg-bernhard#1]
We need a `python3-bernhard` version of this package, how should we proceed? cc @brutasse @vincentbernat

**Comment by vincentbernat** [comment]
It's in Bionic. In Xenial, this is complicated as python-protobuf doesn't have Python 3 support in 2.X and 3.X is not compatible with 2.X. There is a gigantic patch to add Python 3 support to protobuf 2.X for Ubuntu but nobody dared to acknowledge it: https://bugs.launchpad.net/ubuntu/+source/httmock/+bug/1735160.

If you care about Xenial, it should be easier to make your script compatible with Python 2 as well.

**Comment by falzm** [comment]
@vincentbernat luckily we only need this package on bionic instances at this point. Thanks!
